# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  #- name: Projects
  #  url: /#projects
  #  weight: 10
  - name: Home
    url: /
    weight: 10
  - name: About Me
    url: /
    weight: 20
  - name: Experience
    parent: About Me
    url: /#experience
    weight: 10
  - name: Skills
    parent: About Me
    url: /#skills
    weight: 20
  - name: News
    parent: About Me
    url: /#news
    weight: 30
  - name: Research
    url: /#
    weight: 30
  - name: Projects
    parent: Research
    url: /#
    weight: 10
  - name: Publications
    parent: Research
    url: /#
    weight: 20
  - name: Collaborators
    parent: Research
    url: /#
    weight: 30
  - name: Teaching
    url: /#
    weight: 40
  - name: TA
    parent: Teaching
    url: /#
    weight: 10
  - name: Courses
    parent: Teaching
    url: /#
    weight: 30
  - name: Mentorship
    parent: Teaching
    url: /#
    weight: 30
  #- name: Experience & Education
  #  url: /experience
  #  weight: 20
  #- name: Skills
  #  url: /#skills
  #  weight: 30
  #- name: Blog
  #  url: /#blog
  #  weight: 40
  - name: Contact
    url: /contact
    weight: 70
